// ============================================================
// DATA
// ============================================================
const ALL_ITEMS = [
  { e:'🍣', n:'マグロ',   yomi:'まぐろ',   r:'maguro',   en:'Bluefin Tuna',    h:'鮪。赤身の王様',       p:'¥180', lv:1 },
  { e:'🦑', n:'イカ',     yomi:'いか',     r:'ika',      en:'Squid',           h:'烏賊。コリコリ食感',   p:'¥130', lv:1 },
  { e:'🦐', n:'エビ',     yomi:'えび',     r:'ebi',      en:'Shrimp',          h:'海老。甘くてプリプリ', p:'¥150', lv:1 },
  { e:'🐙', n:'タコ',     yomi:'たこ',     r:'tako',     en:'Octopus',         h:'蛸。噛むほど旨い',     p:'¥140', lv:1 },
  { e:'🐠', n:'アジ',     yomi:'あじ',     r:'aji',      en:'Horse Mackerel',  h:'鯵。光物の代表',       p:'¥120', lv:1 },
  { e:'🐟', n:'ブリ',     yomi:'ぶり',     r:'buri',     en:'Yellowtail',      h:'鰤。冬が旬の王者',     p:'¥170', lv:1 },
  { e:'🐟', n:'タイ',     yomi:'たい',     r:'tai',      en:'Sea Bream',       h:'鯛。めでたい魚',       p:'¥180', lv:1 },
  { e:'🐟', n:'サバ',     yomi:'さば',     r:'saba',     en:'Mackerel',        h:'鯖。しめ鯖で絶品',     p:'¥120', lv:1 },
  { e:'🦀', n:'カニ',     yomi:'かに',     r:'kani',     en:'Crab',            h:'蟹。贅沢な一皿',       p:'¥350', lv:1 },
  { e:'🐡', n:'フグ',     yomi:'ふぐ',     r:'fugu',     en:'Pufferfish',      h:'河豚。下関直送',       p:'¥500', lv:1 },
  { e:'🐟', n:'トロ',     yomi:'とろ',     r:'toro',     en:'Fatty Tuna',      h:'大トロ。とろける旨さ', p:'¥350', lv:1 },
  { e:'🥚', n:'玉子',     yomi:'たまご',   r:'tamago',   en:'Egg',             h:'だし巻き。甘くふわふわ',p:'¥100', lv:1 },
  { e:'🐟', n:'イワシ',   yomi:'いわし',   r:'iwashi',   en:'Sardine',         h:'鰯。光物の風味豊か',   p:'¥110', lv:1 },
  { e:'🐟', n:'ハマチ',   yomi:'はまち',   r:'hamati',  en:'Young Yellowtail',h:'ブリの若魚。脂のり抜群',p:'¥150', lv:1 },
  { e:'🐟', n:'サワラ',   yomi:'さわら',   r:'sawara',   en:'Spanish Mackerel',h:'鰆。春が旬の上品な白身',p:'¥160', lv:1 },
  { e:'🐍', n:'ウナギ',   yomi:'うなぎ',   r:'unagi',    en:'Freshwater Eel',  h:'鰻。ふわとろ甘ダレ',   p:'¥250', lv:1 },
  { e:'🐚', n:'アサリ',   yomi:'あさり',   r:'asari',    en:'Clam',            h:'浅蜊。旨味たっぷり',   p:'¥130', lv:1 },
  { e:'🐟', n:'シラス',   yomi:'しらす',   r:'shirasu',  en:'Whitebait',       h:'北九州近海の幸',       p:'¥120', lv:1 },
  { e:'🐟', n:'ニシン',   yomi:'にしん',   r:'nishinn',   en:'Herring',         h:'鰊。数の子の親魚',     p:'¥130', lv:1 },
  { e:'🌿', n:'ノリ',     yomi:'のり',     r:'nori',     en:'Seaweed',         h:'海苔。磯の香り豊か',   p:'¥80',  lv:1 },
  { e:'🐟', n:'カマス',   yomi:'かます',   r:'kamasu',   en:'Barracuda',       h:'魳。塩焼きも絶品',     p:'¥140', lv:1 },
  { e:'🐟', n:'メバル',   yomi:'めばる',   r:'mebaru',   en:'Rockfish',        h:'眼張。旨い白身魚',     p:'¥150', lv:1 },
  { e:'🐟', n:'サンマ',   yomi:'さんま',   r:'sannma',    en:'Pacific Saury',   h:'秋刀魚。秋が旬の光物', p:'¥130', lv:1 },
  { e:'🦪', n:'カキ',    yomi:'かき',     r:'kaki',     en:'Oyster',          h:'牡蠣。海のミルク',     p:'¥180', lv:1 },
  { e:'🐟', n:'マダイ',  yomi:'まだい',   r:'madai',    en:'Red Sea Bream',   h:'真鯛。淡泊な上品白身', p:'¥180', lv:1 },
  { e:'🐟', n:'タラ',    yomi:'たら',     r:'tara',     en:'Cod',             h:'鱈。ふわふわ白身',     p:'¥140', lv:1 },
  { e:'🐟', n:'スズキ',  yomi:'すずき',   r:'suzuki',   en:'Sea Bass',        h:'鱸。夏が旬の白身',     p:'¥160', lv:1 },
  { e:'🐟', n:'ホヤ',    yomi:'ほや',     r:'hoya',     en:'Sea Squirt',      h:'海のパイナップル',     p:'¥150', lv:1 },
  { e:'🫚', n:'ガリ',    yomi:'がり',     r:'gari',     en:'Pickled Ginger',  h:'口直しの生姜漬け',     p:'無料', lv:1 },
  { e:'🐟', n:'ツナ',    yomi:'つな',     r:'tsuna',    en:'Tuna Mayo',       h:'ツナマヨ。子どもに人気',p:'¥110', lv:1 },
  { e:'🌽', n:'コーン',  yomi:'こーん',   r:'ko-nn',    en:'Corn',            h:'甘くてプチプチ',       p:'¥100', lv:1 },
  { e:'🧀', n:'チーズ',  yomi:'ちーず',   r:'ti-zu',   en:'Cheese',          h:'濃厚とろとろ',         p:'¥110', lv:1 },
  { e:'🥑', n:'アボカド',yomi:'あぼかど', r:'abokado',  en:'Avocado',         h:'とろける食感',         p:'¥120', lv:1 },
  { e:'🐟', n:'サーモン', yomi:'さーもん', r:'samon',    en:'Salmon',          h:'鮭。とろける脂',       p:'¥160', lv:2 },
  { e:'🥚', n:'イクラ',   yomi:'いくら',   r:'ikura',    en:'Salmon Roe',      h:'プチプチ食感',         p:'¥220', lv:2 },
  { e:'🐚', n:'ホタテ',   yomi:'ほたて',   r:'hotate',   en:'Scallop',         h:'帆立。甘みが絶品',     p:'¥200', lv:2 },
  { e:'🐟', n:'アナゴ',   yomi:'あなご',   r:'anago',    en:'Sea Eel',         h:'穴子。ふわふわ',       p:'¥190', lv:2 },
  { e:'🐟', n:'コハダ',   yomi:'こはだ',   r:'kohada',   en:'Gizzard Shad',    h:'江戸前の真骨頂',       p:'¥150', lv:2 },
  { e:'🐟', n:'カツオ',   yomi:'かつお',   r:'katsuo',   en:'Bonito',          h:'鰹。たたきも絶品',     p:'¥160', lv:2 },
  { e:'🦔', n:'ウニ',     yomi:'うに',     r:'uni',      en:'Sea Urchin',      h:'雲丹。濃厚クリーミー', p:'¥450', lv:2 },
  { e:'🐚', n:'アワビ',   yomi:'あわび',   r:'awabi',    en:'Abalone',         h:'鮑。磯の香り豊か',     p:'¥600', lv:2 },
  { e:'🐟', n:'ヒラメ',   yomi:'ひらめ',   r:'hirame',   en:'Flounder',        h:'平目。上品な白身',     p:'¥200', lv:2 },
  { e:'🐟', n:'中トロ',  yomi:'ちゅうとろ',r:'tyuutoro',  en:'Medium Fatty Tuna',h:'大トロと赤身の中間',  p:'¥280', lv:2 },
  { e:'🐟', n:'カンパチ',yomi:'かんぱち', r:'kannpati', en:'Amberjack',       h:'間八。コリコリ歯ごたえ',p:'¥180', lv:2 },
  { e:'🐟', n:'エンガワ',yomi:'えんがわ', r:'enngawa',   en:'Flatfish Fin',    h:'縁側。コリコリ絶品',   p:'¥160', lv:2 },
  { e:'🐟', n:'のどぐろ',yomi:'のどぐろ', r:'nodoguro', en:'Blackthroat Seaperch',h:'喉黒。高級白身魚',  p:'¥350', lv:2 },
  { e:'🐟', n:'ネギトロ',yomi:'ねぎとろ', r:'negitoro', en:'Minced Tuna',     h:'まぐろの旨みとネギ',   p:'¥160', lv:2 },
  { e:'🐟', n:'しめさば',yomi:'しめさば', r:'shimesaba',en:'Pickled Mackerel', h:'〆鯖。酢と塩で〆た逸品',p:'¥140', lv:2 },
  { e:'🦐', n:'アマエビ',yomi:'あまえび', r:'amaebi',   en:'Sweet Shrimp',    h:'甘海老。生でとろける甘さ',p:'¥200', lv:2 },
  { e:'🐚', n:'ホッキガイ',yomi:'ほっきがい',r:'hokkigai',en:'Surf Clam',     h:'北寄貝。甘みとコリコリ感',p:'¥180', lv:2 },
  { e:'🐚', n:'ツブ貝',  yomi:'つぶがい', r:'tsubugai', en:'Whelk',           h:'螺貝。コリコリ食感',   p:'¥190', lv:2 },
  { e:'🥚', n:'たらこ',  yomi:'たらこ',   r:'tarako',   en:'Pollock Roe',     h:'鱈子。プチプチ旨み',   p:'¥150', lv:2 },
  { e:'🥚', n:'とびっこ',yomi:'とびっこ', r:'tobikko',  en:'Flying Fish Roe', h:'飛び子。プチプチ食感', p:'¥160', lv:2 },
  { e:'🍙', n:'いなり',  yomi:'いなり',   r:'inari',    en:'Inari Sushi',     h:'稲荷。甘い油揚げ',     p:'¥100', lv:2 },
  { e:'🍤', n:'てんぷら',yomi:'てんぷら', r:'tennpura',  en:'Tempura',         h:'天ぷら。サクサク衣',   p:'¥160', lv:2 },
  { e:'🌿', n:'かっぱ巻き',yomi:'かっぱまき',r:'kappamaki',en:'Cucumber Roll',h:'きゅうりのさっぱり巻き',p:'¥110', lv:2 },
  { e:'🍣', n:'てっか巻き',yomi:'てっかまき',r:'tekkamaki',en:'Tuna Roll',    h:'鉄火巻き。まぐろの細巻',p:'¥130', lv:2 },
  { e:'🍵', n:'あがり',  yomi:'あがり',   r:'agari',    en:'Green Tea',       h:'お寿司屋さんのお茶',   p:'無料', lv:2 },
  { e:'🫚', n:'わさび',  yomi:'わさび',   r:'wasabi',   en:'Wasabi',          h:'山葵。ピリっと辛い',   p:'', lv:2 },
  { e:'🍱', n:'ちらし寿司',yomi:'ちらしずし',r:'tirashizushi',en:'Chirashi Sushi',h:'散らし寿司。彩り豊か',p:'¥580', lv:2 },
  { e:'🍜', n:'みそしる', yomi:'みそしる', r:'misoshiru',en:'Miso Soup',       h:'お味噌汁。ほっこり',   p:'¥110', lv:2 },
  { e:'🥚', n:'ちゃわんむし',yomi:'ちゃわんむし',r:'chawannmushi',en:'Steamed Egg Custard',h:'茶碗蒸し。とろとろ',p:'¥160', lv:2 },
  { e:'🔥', n:'あぶりサーモン',yomi:'あぶりさーもん',r:'aburisamonn',en:'Torched Salmon',h:'炙り鮭。香ばしさ抜群',p:'¥200', lv:2 },
  { e:'🥢', n:'軍艦巻き', yomi:'ぐんかんまき', r:'gunnkannmaki', en:'Gunkan Roll', h:'のりで囲った特殊形', p:'¥160', lv:2 },
  { e:'🙇', n:'へいいらっしゃい', yomi:'へいいらっしゃい', r:'heiirassyai', en:'Hey, welcome!', h:'威勢のいい職人の掛け声', p:'', lv:2 },
  { e:'🙏', n:'ありがとうございます', yomi:'ありがとうございます', r:'arigatougozaimasu', en:'Thank you very much', h:'感謝の気持ちを込めて', p:'', lv:2 },
  { e:'🔪', n:'三枚おろし', yomi:'さんまいおろし', r:'sannmaioroshi', en:'Three-piece fillet', h:'魚を三枚に下ろす技法', p:'', lv:2 },
  { e:'🍚', n:'シャリを握る', yomi:'しゃりをにぎる', r:'sharionigiru', en:'Shaping the sushi rice', h:'酢飯を手で成形する', p:'', lv:2 },
  { e:'🐟', n:'活け締め', yomi:'いけじめ', r:'ikejime', en:'Ikejime', h:'鮮度を保つ締め方', p:'', lv:2 },
  { e:'🐟', n:'びんちょうまぐろ',yomi:'びんちょうまぐろ',r:'binnchomaguro',en:'Albacore Tuna',h:'ビンチョウ。あっさり白いまぐろ',p:'¥130', lv:3 },
  { e:'🦐', n:'ボタンエビ',yomi:'ぼたんえび',r:'botannebi',en:'Botan Shrimp',h:'牡丹海老。とろける甘さ最高峰',p:'¥400', lv:3 },
  { e:'🐚', n:'みる貝',  yomi:'みるがい', r:'mirugai',  en:'Geoduck Clam',    h:'海松貝。シャキシャキ磯の香り',p:'¥300', lv:3 },
  { e:'🔥', n:'炙りで仕上げる', yomi:'あぶりでしあげる', r:'aburideshiageru', en:'Torched to perfection', h:'バーナーで香ばしく', p:'', lv:3 },
  { e:'🍣', n:'おまかせコース', yomi:'おまかせこーす', r:'omakasekosu', en:"Chef's choice", h:'職人に全部任せる', p:'¥8800', lv:2 },
  { e:'🔪', n:'かつらむき', yomi:'かつらむき', r:'katuramuki', en:'Katsuramuki', h:'薄く円形に剥く包丁技', p:'', lv:2 },
  { e:'🚢', n:'唐戸市場から直送', yomi:'からといちばからちょくそう', r:'karatoitibakara', en:'Direct from Karato', h:'関門海峡の鮮魚市場', p:'', lv:3 },
  { e:'🏯', n:'小倉城', yomi:'こくらじょう', r:'kokurajo', en:'Kokura Castle', h:'北九州のシンボル', p:'', lv:2 },
  { e:'🌉', n:'門司港レトロ', yomi:'もじこうれとろ', r:'mojikoretoro', en:'Mojiko Retro District', h:'大正ロマンあふれる港町', p:'', lv:2 },
  { e:'🌉', n:'関門橋', yomi:'かんもんきょう', r:'kannmonnkyou', en:'Kanmon Bridge', h:'本州と九州をつなぐ橋', p:'', lv:2 },
  { e:'🚢', n:'関門海峡', yomi:'かんもんかいきょう', r:'kannmonnkaikyo', en:'Kanmon Strait', h:'本州と九州を分かつ海峡', p:'', lv:2 },
  { e:'🏭', n:'八幡製鉄所', yomi:'やわたせいてつじょ', r:'yawataseitetsujo', en:'Yawata Steel Works', h:'明治日本の産業遺産', p:'', lv:3 },
  { e:'🌸', n:'河内藤園', yomi:'かわちふじえん', r:'kawatifujienn', en:'Kawachi Wisteria Garden', h:'圧巻の藤棚', p:'', lv:2 },
  { e:'🌊', n:'洞海湾', yomi:'どうかいわん', r:'dokaikan', en:'Dokai Bay', h:'工場夜景が映える湾', p:'', lv:2 },
  { e:'🎡', n:'皿倉山', yomi:'さらくらやま', r:'sarakurayama', en:'Sarakura Mountain', h:'百万ドルの夜景スポット', p:'', lv:2 },
  { e:'🍜', n:'焼きうどん', yomi:'やきうどん', r:'yakiudonn', en:'Yaki Udon', h:'北九州発祥のソウルフード', p:'', lv:1 },
  { e:'🍱', n:'かしわめし', yomi:'かしわめし', r:'kashiwameshi', en:'Kashiwa Meshi', h:'折尾駅の名物駅弁', p:'', lv:2 },
  { e:'🐟', n:'唐戸市場', yomi:'からといちば', r:'karatoitiba', en:'Karato Fish Market', h:'関門の新鮮魚介が並ぶ', p:'', lv:2 },
  { e:'🏙️', n:'北九州市', yomi:'きたきゅうしゅうし', r:'kitakyushushi', en:'Kitakyushu City', h:'政令指定都市・人口約93万人', p:'', lv:2 },
  { e:'🌅', n:'響灘', yomi:'ひびきなだ', r:'hibikinada', en:'Hibiki Sea', h:'北九州市西側の海域', p:'', lv:2 },
  { e:'🎆', n:'北九州まつり', yomi:'きたきゅうしゅうまつり', r:'kitakyushomatsuri', en:'Kitakyushu Festival', h:'夏の一大イベント', p:'', lv:2 },
  { e:'🌊', n:'北九州市観光局', yomi:'きたきゅうしゅうしかんこうきょく', r:'kitakyushukannkoukyoku', en:'Kitakyushu Tourism', h:'北九州の魅力を全国へ', p:'', lv:2, tag:'公式' },
  { e:'🎓', n:'門司港プログラミング道場', yomi:'もじこうぷろぐらみんぐどうじょう', r:'mojikopuroguraminngudojo', en:'Mojiko Programming Dojo', h:'子どもたちのIT教育', p:'', lv:3, tag:'主催' },
  { e:'🍣', n:'北九州寿司の都構想', yomi:'きたきゅうしゅうすしのみやこ', r:'kitakyushusushinomiyako', en:'Kitakyushu Sushi Capital', h:'寿司で街を活性化', p:'', lv:3, tag:'公式' },
];

const QUIZZES = [
  { q:'北九州市にある明治の世界遺産の製鉄所は？', hint:'ひらがな・漢字・ローマ字で', a:'yawataseitetsujo', display:'八幡製鉄所', ja:['やわたせいてつじょ','八幡製鉄所','八幡製鐵所'] },
  { q:'関門海峡をはさんだ対岸の山口県の市は？', hint:'ひらがな・漢字・ローマ字で', a:'shimonoseki', display:'下関', ja:['しものせき','下関'] },
  { q:'北九州発祥のソウルフードは？', hint:'やき＋うどん', a:'yakiudon', display:'焼きうどん', ja:['やきうどん','焼きうどん','焼うどん'] },
  { q:'小倉城を築いた武将の名字は？（細川）', hint:'ひらがな・漢字・ローマ字で', a:'hosokawa', display:'細川（忠興）', ja:['ほそかわ','細川'] },
  { q:'寿司のご飯を何という？', hint:'しゃり', a:'shari', display:'シャリ', ja:['しゃり'] },
  { q:'北九州市は何区で構成されている？（数字で）', hint:'ひらがな・漢字・数字', a:'nana', display:'七（7区）', ja:['なな','七','7'] },
  { q:'門司港名物の果物は何？', hint:'バナナの叩き売り', a:'banana', display:'バナナ', ja:['ばなな'] },
  { q:'河豚を調理するために必要なものは？', hint:'めんきょ', a:'menkyo', display:'免許', ja:['めんきょ','免許'] },
  { q:'北九州の百万ドルの夜景が見える山は？', hint:'さらくらやま', a:'sarakurayama', display:'皿倉山', ja:['さらくらやま','皿倉山'] },
  { q:'折尾駅名物の駅弁は？', hint:'かしわめし', a:'kashiwameshi', display:'かしわめし', ja:['かしわめし','かしわ飯','柏飯','柏めし'] },
  { q:'門司港の重要文化財の駅名は？', hint:'もじこうえき', a:'mojikoeki', display:'門司港駅', ja:['もじこうえき','門司港駅'] },
  { q:'北九州まつりが開催される季節は？', hint:'夏', a:'natsu', display:'夏', ja:['なつ','夏'] },
];

const POWERUPS = [
  { id:'x2',    icon:'🔥', name:'炙りモード',    desc:'スコア2倍＆速度1.5倍！30秒間', duration:30, color:'rgba(192,57,43,.3)' },
  { id:'slow',  icon:'🧊', name:'冷却タイム',    desc:'ベルト半速！30秒間', duration:30, color:'rgba(26,188,156,.2)' },
  { id:'combo', icon:'⚡', name:'コンボ激化',    desc:'コンボ倍率2倍！30秒間', duration:30, color:'rgba(243,156,18,.2)' },
  { id:'short', icon:'🎯', name:'おまかせ',      desc:'短いネタだけ！20秒間', duration:20, color:'rgba(52,152,219,.2)' },
];

const BADGES = [
  { id:'aji',    e:'🐟', name:'アジの握り',   cond:'累計500点',      axis:'score', th:500    },
  { id:'ika',    e:'🦑', name:'イカ職人',      cond:'累計2,000点',    axis:'score', th:2000   },
  { id:'tako',   e:'🐙', name:'タコの達人',    cond:'累計5,000点',    axis:'score', th:5000   },
  { id:'maguro', e:'🍣', name:'マグロ棟梁',    cond:'累計15,000点',   axis:'score', th:15000  },
  { id:'uni',    e:'🦔', name:'ウニの匠',      cond:'累計40,000点',   axis:'score', th:40000  },
  { id:'fugu',   e:'🐡', name:'フグ免許皆伝',  cond:'累計100,000点',  axis:'score', th:100000 },
  { id:'wpm20',  e:'🍚', name:'シャリ打ち',    cond:'WPM 20以上',    axis:'wpm',   th:20  },
  { id:'wpm40',  e:'🔪', name:'包丁さばき',    cond:'WPM 40以上',    axis:'wpm',   th:40  },
  { id:'wpm60',  e:'🌊', name:'関門の流れ',    cond:'WPM 60以上',    axis:'wpm',   th:60  },
  { id:'wpm80',  e:'⚡', name:'神速の握り',    cond:'WPM 80以上',    axis:'wpm',   th:80  },
  { id:'wpm100', e:'🏯', name:'小倉城主',      cond:'WPM 100以上',   axis:'wpm',   th:100 },
  { id:'combo5', e:'🔥', name:'炙り師',        cond:'5コンボ達成',   axis:'combo', th:5   },
  { id:'acc100', e:'💯', name:'完璧な一皿',    cond:'正確度100%',    axis:'acc',   th:100 },
  { id:'hard',   e:'🚢', name:'唐戸直送',      cond:'板長モードクリア', axis:'diff', th:1 },
  { id:'all',    e:'🏆', name:'寿司の都の王',  cond:'全バッジ制覇',  axis:'all',   th:14  },
];

const RANKS = [
  { min:0,    title:'🍚 シャリ見習い', msg:'基本から練習しよう！' },
  { min:100,  title:'🐟 アジの握り',   msg:'もう少しで一人前！' },
  { min:400,  title:'🦑 イカの達人',   msg:'いい調子です！' },
  { min:900,  title:'🐙 タコ職人',     msg:'かなりの腕前！' },
  { min:1600, title:'🍣 マグロ棟梁',   msg:'本物の寿司職人！' },
  { min:2500, title:'🏆 北九州の伝説', msg:'まさに伝説の域！' },
];

const LB_DATA = [
  { name:'田中 太郎', score:2840, wpm:92, acc:'97%' },
  { name:'山田 花子', score:2320, wpm:85, acc:'99%' },
  { name:'鈴木 一郎', score:1980, wpm:78, acc:'95%' },
  { name:'佐藤 美咲', score:1620, wpm:71, acc:'93%' },
  { name:'中村 健太', score:1200, wpm:65, acc:'91%' },
  { name:'小林 あゆみ', score:980, wpm:58, acc:'89%' },
  { name:'加藤 直樹', score:740, wpm:51, acc:'86%' },
  { name:'伊藤 さくら', score:580, wpm:44, acc:'88%' },
  { name:'松本 剛', score:420, wpm:37, acc:'84%' },
  { name:'木村 裕子', score:280, wpm:29, acc:'80%' },
];
